#input and output paths are absolute paths 
#example: "C:\Users\dm2\AccessionATF\All_tests\Audio"

input_path: C:\Users\dm2\AccessionATF\input_output\quick_test
output_path: C:\Users\dm2\AccessionATF\ATAT_GitLab\Jitter_Buffer_Testing\new_repo_testing


#If making adjustments to the Jitter Buffer, please provide the max jitter buffer size to ensure your
#output files do not get clipped (ms)

delay: 2500