#NOTE: YAML syntax requires a space between a colon and the input value or else it will raise an error!

#Login info for Router
---
Login_info:
 IP_address: '192.168.8.1'
 Username: 'root'
 Password: '!BeeEmDubyuu4'

Device: wlan-sta

#List of Network Conditions 

       #  :=  TIME [ JITTER [ CORRELATION ]]]
              # [ distribution { normal | pareto |  paretonormal } ]

       # LOSS := loss { random PERCENT [ CORRELATION ]  |
                      # gemodel p [ r [ 1-h [ 1-k ]]] }  [ ecn ]

#Network_parameters:
# to do
# turn in to list of dictionaries
# parsing error checks for incorrect structure
# wlan-sta and router interface dictionary entry

Commands:
 - loss:
    type: random
    value: 20
   delay:
    time: 200
    jitter: normal 
    distribution: 50
    
 - loss:
    type: gemodel
    value: 1 3
   delay:
    time: 90
    jitter: normal 
    distribution: 22

 - loss:
    type: 
    value:  
   delay:
    time:
    jitter: 
    distribution:
    
 - loss:
    type: 
    value:  
   delay:
    time:
    jitter: 
    distribution:
...